### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Mentors4EDU**
Invert UI link not found: https://blobscdn.gitbook.com/v0/b/gitbook-28427.appspot.com/o/spaces%2F-Lvv5ZdlY65NsFAqv-z0%2Favatar.png?generation=1577373436605130&alt=media

### CODE REVIEW

**Comment by behoyh** [comment]
The links are working fine for me

**Comment by Mentors4EDU** [comment]
Then set the GitBook to public not private, because the link says not found untop so unsure why it isn't working.

Screenshot from 2020-05-20 07-48-49

**Comment by Mentors4EDU** [comment]
@behoyh Log off GitHub and GitBook and try going to:
https://blobscdn.gitbook.com/v0/b/gitbook-28427.appspot.com/o/assets%2F-Lvv5ZdlY65NsFAqv-z0%2F-LwKi8e0TsqbOXBpLfSW%2F-LwKjfatlnXrp2yFIT86%2Fimage.png?alt=media&token=6a33f50f-08ba-496a-a085-e0f823132cc0

It won't load

**Comment by behoyh** [comment]
Actually it’s not working, you’re right. Got to use different image hosting.

**Pull request merged**
